version: '3'

services:

  app:
    image: node:14-slim
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace:cached
    environment:
      NODE_ENV: development
    working_dir: /workspace
    command: npm run dev:server

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:
